version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: compraki
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: compraki
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    container_name: compraki-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/compraki  

volumes:
  postgres-data:
